### ISSUE TITLE
sphinx setup?

### ISSUE THREAD

**Issue by rainwoodman** [desihub/desitemplate#1]
I noticed desispec has a sphinx Makefile and conf.py, but not described in the template. Are there standard protocols to set up the sphinx documentation?

**Comment by weaverba137** [comment]
The desitemplate product *is* the guide to setting up Sphinx documentation.  There are also extensive instructions in the top-level README.rst file.  I'm not sure I understand what is missing.

**Comment by weaverba137** [comment]
Hmm, it looks like I may have misunderstood the question.  We are moving to a system where those files are necessary for ReadTheDocs, so those files should remain in place in desispec, though they may need to be tweaked a little bit.  Eventually the template will be updated to reflect that change.  See #2.

**Comment by rainwoodman** [comment]
+1 to #2 

It is also easier to understand if there is a ready to use Makefile in doc directory.

Just form the information in Readme it is unclear how to bootstrap the documentation -- it mentioned names of packages but that still leaves a lot of space for imaginations.

One more question: do we also run sphinx-autogen on the python modules to automatically generate the .rst files for each module? Shall these products be committed to doc/ or kept off the git tree?
